extern "C" {
#include "libavutil/frame.h"
}

#include "avutil/pixfmt.h"

using namespace v8;

namespace ffmpeg {
namespace avutil {

void AVPixelFormat::Init(Handle<Object> exports) {
  NanScope();

  Local<Object> obj = NanNew<Object>();

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_NONE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUYV422);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB24);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR24);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV410P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV411P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GRAY8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_MONOWHITE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_MONOBLACK);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_PAL8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVJ420P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVJ422P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVJ444P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_UYVY422);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_UYYVYY411);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR4);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR4_BYTE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB4);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB4_BYTE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_NV12);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_NV21);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_ARGB);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGBA);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_ABGR);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGRA);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GRAY16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GRAY16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV440P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVJ440P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB48BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB48LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB565BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB565LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB555BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB555LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR565BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR565LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR555BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR555LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_VAAPI_MOCO);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_VAAPI_IDCT);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_VAAPI_VLD);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_DXVA2_VLD);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB444LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB444BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR444LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR444BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YA8);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_Y400A);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GRAY8A);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR48BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR48LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_VDA_VLD);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP16LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P_LIBAV);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P_LIBAV);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P9BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P9LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P10BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P10LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA420P16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P16LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_VDPAU);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_XYZ12LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_XYZ12BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_NV16);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_NV20LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_NV20BE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGBA64BE_LIBAV);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGBA64LE_LIBAV);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGRA64BE_LIBAV);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGRA64LE_LIBAV);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YVYU422);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_VDA);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YA16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YA16LE);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRAP_LIBAV);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRAP16BE_LIBAV);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRAP16LE_LIBAV);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_QSV);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_0RGB);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_RGB0);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_0BGR);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BGR0);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA444P);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVA422P);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P12BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P12LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P14BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV420P14LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P12BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P12LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P14BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV422P14LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P12BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P12LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P14BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUV444P14LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP12BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP12LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP14BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRP14LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRAP);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRAP16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_GBRAP16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_YUVJ411P);

  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_BGGR8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_RGGB8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_GBRG8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_GRBG8);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_BGGR16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_BGGR16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_RGGB16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_RGGB16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_GBRG16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_GBRG16BE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_GRBG16LE);
  NODE_DEFINE_CONSTANT(obj, AV_PIX_FMT_BAYER_GRBG16BE);

  exports->Set(NanNew("AVPixelFormat"), obj);
}

void AVColorPrimaries::Init(Handle<Object> exports) {
  NanScope();

  Local<Object> obj = NanNew<Object>();

  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_RESERVED0);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_BT709);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_UNSPECIFIED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_RESERVED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_BT470M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_BT470BG);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_SMPTE170M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_SMPTE240M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_FILM);
  NODE_DEFINE_CONSTANT(obj, AVCOL_PRI_BT2020);

  exports->Set(NanNew("AVColorPrimaries"), obj);
}

void AVColorTransferCharacteristic::Init(Handle<Object> exports) {
  NanScope();

  Local<Object> obj = NanNew<Object>();

  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_RESERVED0);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_BT709);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_UNSPECIFIED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_RESERVED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_GAMMA22);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_GAMMA28);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_SMPTE170M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_SMPTE240M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_LINEAR);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_LOG);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_LOG_SQRT);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_IEC61966_2_4);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_BT1361_ECG);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_IEC61966_2_1);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_BT2020_10);
  NODE_DEFINE_CONSTANT(obj, AVCOL_TRC_BT2020_12);

  exports->Set(NanNew("AVColorTransferCharacteristic"), obj);
}

void AVColorSpace::Init(Handle<Object> exports) {
  NanScope();

  Local<Object> obj = NanNew<Object>();

  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_RGB);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_BT709);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_UNSPECIFIED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_RESERVED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_FCC);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_BT470BG);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_SMPTE170M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_SMPTE240M);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_YCOCG);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_YCGCO);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_BT2020_NCL);
  NODE_DEFINE_CONSTANT(obj, AVCOL_SPC_BT2020_CL);

  NODE_SET_METHOD(obj, "getColorspaceName", GetColorspaceName);

  exports->Set(NanNew("AVColorSpace"), obj);
}

NAN_METHOD(AVColorSpace::GetColorspaceName) {
  NanScope();

  if (!args[0]->IsNumber())
    return NanThrowTypeError("getColorspaceName: AVColorSpace enum required");

  enum ::AVColorSpace val =
    static_cast<enum ::AVColorSpace>(args[0]->Uint32Value());
  const char* name = av_get_colorspace_name(val);
  if (name)
    NanReturnValue(NanNew<String>(name));
  else
    NanReturnEmptyString();
}

void AVColorRange::Init(Handle<Object> exports) {
  NanScope();

  Local<Object> obj = NanNew<Object>();

  NODE_DEFINE_CONSTANT(obj, AVCOL_RANGE_UNSPECIFIED);
  NODE_DEFINE_CONSTANT(obj, AVCOL_RANGE_MPEG);
  NODE_DEFINE_CONSTANT(obj, AVCOL_RANGE_JPEG);

  exports->Set(NanNew("AVColorRange"), obj);
}

void AVChromaLocation::Init(Handle<Object> exports) {
  NanScope();

  Local<Object> obj = NanNew<Object>();

  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_UNSPECIFIED);
  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_LEFT);
  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_CENTER);
  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_TOPLEFT);
  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_TOP);
  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_BOTTOMLEFT);
  NODE_DEFINE_CONSTANT(obj, AVCHROMA_LOC_BOTTOM);

  exports->Set(NanNew("AVChromaLocation"), obj);
}

}  // namespace avutil
}  // namespace ffmpeg
